# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_id', models.IntegerField()),
                ('english_title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('canonical_title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('age_rating_guide', models.CharField(blank=True, max_length=50, null=True)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('poster_image_link', models.TextField(blank=True, null=True)),
                ('cover_image_link', models.TextField(blank=True, null=True)),
                ('episode_count', models.IntegerField(blank=True, null=True)),
                ('episode_length', models.IntegerField(blank=True, null=True)),
                ('youtube_video_id', models.TextField(blank=True, null=True)),
                ('show_type', models.CharField(blank=True, max_length=50, null=True)),
                ('nsfw', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='categories.Categorie')),
                ('genres', models.ManyToManyField(to='genres.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
