# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
