# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='end_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='start_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
