# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_auto_20170903_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
        migrations.RemoveField(
            model_name='search',
            name='anime',
        ),
    ]
