# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_id', models.IntegerField()),
                ('content', models.TextField()),
                ('content_formatted', models.TextField(blank=True, null=True)),
                ('likes_count', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('spoiler', models.BooleanField(default=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.Anime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
